set viminfo+=n~/.config/vim/viminfo
syn on
set exrc
set incsearch
set hidden autoread
set number relativenumber
set nojoinspaces
set gdefault
set undofile undodir=~/.local/share/nvim/undo//
set shiftwidth=4 shiftround 
set softtabstop=4 tabstop=4 expandtab
set ttimeout timeoutlen=3000 ttimeoutlen=50
set clipboard+=unnamed
set shortmess=xtToOFc
set grepprg=rg\ --vimgrep
set completeopt=menuone,noinsert,noselect
set rtp+=/usr/local/opt/fzf
set tags=./tags;,./.tags;,
set conceallevel=1
set directory=~/.local/share/vim/swp//
set backspace=indent,eol,start
set ruler
set nobackup
set timeout
set laststatus=2
set showcmd
set wildmenu
set smartindent
filetype indent plugin on

let mapleader = " "
nnoremap <Up> <c-y>
nnoremap <Down> <c-e>
vnoremap <leader>p "_dP
nnoremap <leader>r :call system('ctags -R -o .tags')<cr>
nnoremap <leader>b :call myfunctions#Buffers()<cr>
nnoremap <expr> <leader>o filter(range(1, winnr('$')), 'getwinvar(v:val, "&ft") == "qf"')==[] ? ':cope<cr>' : ':ccl<cr>' 
let g:hasbeenset = 1
