set nocompatible
set ttimeout timeoutlen=3000 ttimeoutlen=50
set timeout
set autoread
set laststatus=2
set ruler
set backspace=indent,eol,start
set nobackup
set wildmenu
set incsearch
set smartindent
set showcmd
filetype plugin indent on
syntax on
set number relativenumber
set ignorecase
set smartcase
set confirm
set autowrite
set undofile
set undodir=~/.local/share/nvim/undo//
set viminfo+=n~/.local/share/vim/viminfo
set directory=~/.local/share/vim/swp//
set completeopt=menuone
set scrolloff=3
set shiftwidth=4
set tabstop=4 softtabstop=4
set expandtab
set t_Co=16
set path=.,,/Users/jasoneveleth/code/python/nistsurf/**,
set wildignore=*/.git/*,*/__pycache__/*,*.png,*.jpg,*.jpeg,*.gif,*.swp*,

augroup useful
    autocmd!
    autocmd Colorscheme * highlight BackgroundWarning ctermbg=9 guibg=#be5046
    autocmd Colorscheme * match BackgroundWarning /\%81v/
    autocmd BufWrite * %s/\s\+$//e " deletes trailing whitespace
    autocmd QuickFixCmdPost [^l]* cwindow " opens quickfix window
    autocmd QuickFixCmdPost l* lwindow
augroup END

let mapleader =" "
vnoremap <S-j> :m '>+1<CR>gv=gv
vnoremap <S-k> :m '<-2<CR>gv=gv
nnoremap s <C-w>
nnoremap ]q :cnext<CR>
nnoremap [q :cprev<CR>
nnoremap <silent> <C-L> :nohlsearch<CR>
nnoremap \ :grep<space>
nnoremap <Leader>u <C-^>
nnoremap <Leader>d :call<space>myfunctions#DiffSaved()<CR>
nnoremap <Leader>b :ls<CR>:b<Left>
nnoremap <Leader>r :call system('/usr/local/bin/ctags -R')
nnoremap <Leader>f :find<space>

set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case

hi! Normal ctermbg=NONE guibg=NONE
hi! NonText ctermbg=NONE guibg=NONE
