#!/bin/sh

export PATH="$PATH:/usr/local/sbin:/Users/jasoneveleth/.local/bin/usr/local/sbin:/Users/jasoneveleth/Library/Python/3.7/bin:/Users/jasoneveleth/Library/Python/3.8/bin:/usr/local/lib/ruby/gems/2.7.0/bin:."
export HISTFILE="$HOME/.cache/zsh/.zhistory"
export XDG_CONFIG_HOME="$HOME/.config"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export MPLCONFIGDIR="$XDG_CONFIG_HOME/matplotlib"
export PYLINTHOME="$XDG_CONFIG_HOME/python/pylint.d"
export CABAL_CONFIG="$XDG_CONFIG_HOME/cabal"
export IDLESTARTUP="$XDG_CONFIG_HOME/python/idlerc"
export ICLOUD="/Users/jasoneveleth/Library/Mobile Documents/com~apple~CloudDocs"
export LESSHISTFILE="$HOME/.cache/less/histfile"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export GEM_HOME="$XDG_CONFIG_HOME/gem/ruby/2.7.0"
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export EDITOR="nvim"
