#!/bin/zsh

alias v="nvim"
alias vim="nvim"
alias ta="tmux a -t"
alias directoryPrompt="PS1=\"[%~]\"$'\n'\" $ \""
alias oldPrompt="PS1='%{%K{0}%F{255}%}%m%{%f%k%} %~ $ '"
alias cleanDS="find . -name '*.DS_Store' -type f -delete"
alias ctags="/usr/local/bin/ctags"
alias py="/usr/local/bin/python3.8"
alias ls="\ls -FG"
alias l="ls -lAh"
alias grep="grep --color=auto"
alias path='echo $PATH | tr -s ":" "\n"'
alias ql="qlmanage -p"
alias empty="echo '' >"
alias dh='dirs -v'

alias commit="git commit"
alias add="git add -A"

alias vimrc="v $XDG_CONFIG_HOME/nvim/init.vim"
alias zshrc="v $XDG_CONFIG_HOME/zsh/.zshrc"
alias book="v $HOME/code/web/bookmarks/input.md"

alias nist="cd $HOME/code/python/nistsurf"
alias bump="cd $HOME/Dropbox/bump/"
alias tnist="tmux a -t nist"
alias tbump="tmux a -t bump"
