#!/bin/zsh

function printcolors() {
    for i in {1..256}; do print -P "%F{$i}Color : $i"; done; 
}

# seach history
fh() {
    print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}

# v - open files in ~/.viminfo
v() {
  local files
  files=$(grep '^>' ~/.viminfo | cut -c3- |
          while read line; do
            [ -f "${line/\~/$HOME}" ] && echo "$line"
          done | fzf-tmux -d -m -q "$*" -1) && vim ${files//\~/$HOME}
}

function acp() {
git add .;
git commit -am "$@";
git push;
}

function randomText() {
text=''
for ((i = 0; i < $1; i++));do
    if [[ $(($RANDOM % 10)) < 2 ]];then
        text+=' '
        i+=1
    fi
    text+=$((number = $RANDOM % 10))
done
echo $text
}

BROWNCS_MOUNTPOINT=~/root/code/browncs
BROWNCS_LOGIN=jeveleth

myfuse() {

printf "... attempting to mount brown filesystem for user ${BROWNCS_LOGIN} on local file ${BROWNCS_MOUNTPOINT}\n"

mkdir -p ${BROWNCS_MOUNTPOINT}

sshfs -o defer_permissions "${BROWNCS_LOGIN}@ssh.cs.brown.edu:/home/${BROWNCS_LOGIN}" "${BROWNCS_MOUNTPOINT}"

}

fixfuse() {

printf "... attempting to unmount brown filesystem from local file ${BROWNCS_MOUNTPOINT}\n"

diskutil unmount force "${BROWNCS_MOUNTPOINT}"

rmdir "${BROWNCS_MOUNTPOINT}"

}
