#!/bin/sh

export PATH="/Users/jasoneveleth/.local/bin/usr/local/sbin:/Users/jasoneveleth/Library/Python/3.7/bin:$PATH"
export VIMINIT="source $HOME/.config/vim/vimrc"
export HISTFILE="$HOME/.config/zsh/.zhistory"
export PYTHONSTARTUP="$HOME/.config/python/pythonrc"
export MPLCONFIGDIR="$HOME/.config/matplotlib"
# export ZDOTDIR="$HOME/.config/zsh"
export PYLINTHOME="$HOME/.config/python/pylint.d"
export CABAL_CONFIG="$HOME/.config/cabal"
export IDLESTARTUP="$HOME/.config/python/idlerc"
export XDG_CONFIG_HOME="$HOME/.config/"
export ICLOUD=/Users/jasoneveleth/Library/Mobile\ Documents/com~apple~CloudDocs
export LESSHISTFILE=-

